site_name: RDAP Conformance Tool Users Manual
site_url: https://icann.github.io/rdap-conformance-tool
theme:
  name: material
  palette:
    scheme: slate
  features:
    - search.share
    - navigation.tracking
  favicon: images/favicon.png
  logo: images/icann-logo-tagline-white-en_680x152.webp
plugins:
  - search
  - autorefs
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print Site'
      print_page_basename: 'print_page'
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
nav:
  - 'overview.md'
  - 'queries_rate_limits.md'
  - 'configuration.md'
  - 'std_95.md'
  - 'gtld_2019_tests.md'
  - 'references.md'