site_name: RDAP Conformance Tool Users Manual
site_url: https://icann.github.io/rdap-conformance-tool
theme:
  name: material
  palette:
    scheme: slate
  features:
    - search.share
    - navigation.tracking
  favicon: images/favicon.png
  logo: images/icann-logo-tagline-white-en_680x152.webp
plugins:
  - search
  - autorefs
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print Site'
      print_page_basename: 'print_page'
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
nav:
  - 'index.md'
  - 'overview.md'
  - 'queries_rate_limits.md'
  - 'configuration.md'
  - 'test_categories.md'
  - 'test_results.md'
  - STD 95 Tests:
    - std_95/general.md
    - std_95/common_structures.md
    - std_95/object_classes.md
    - std_95/response.md
  - 2019 gTLD profile Tests:
    - Technical Implemenation Guide:
      - 2019_gtld/tig/general.md
      - 2019_gtld/tig/registry.md
      - 2019_gtld/tig/registrar.md
    - Response Profile:
      - 2019_gtld/response/general.md
      - 2019_gtld/response/miscellaneous.md
      - 2019_gtld/response/domain.md
      - 2019_gtld/response/nameserver.md
      - 2019_gtld/response/domain_entities_general.md
      - 2019_gtld/response/domain_entities_registry.md
      - 2019_gtld/response/domain_entities_registrar.md
      - 2019_gtld/response/entity_registrar.md
  - 2024 gTLD profile Tests:
    - 2024_gtld/from_2019.md
    - Technical Implemenation Guide:
      - 2024_gtld/tig/general.md
    - Response Profile:
      - 2024_gtld/response/general.md
      - 2024_gtld/response/domain.md
      - 2024_gtld/response/domain_registrant.md
      - 2024_gtld/response/domain_technical.md
  - 'references.md'