package org.icann.rdapconformance.validator.workflow.profile.rdap_response.nameserver;

import org.icann.rdapconformance.validator.QueryContext;
import org.icann.rdapconformance.validator.configuration.RDAPValidatorConfiguration;
import org.icann.rdapconformance.validator.workflow.profile.rdap_response.QueryValidation;
import org.icann.rdapconformance.validator.workflow.rdap.RDAPQueryType;
import org.icann.rdapconformance.validator.workflow.rdap.RDAPValidatorResults;

public final class ResponseValidation4Dot1Query extends QueryValidation {

  public ResponseValidation4Dot1Query(QueryContext qctx) {

    // Error code: -49100 (ldhName validation)
    // Note: -49101 (unicodeName validation) is generated by QueryValidation base class
    super(qctx, "4.1", -49100);
  }

  @Override
  public String getGroupName() {
    return "rdapResponseProfile_4_1_Validation";
  }

  @Override
  public boolean doLaunch() {
    return queryType.equals(RDAPQueryType.NAMESERVER);
  }
}
